notifications:
    email:
        - dean@airdb.com
dist: trusty
sudo: required
services:
      - docker
language: go
go:
    - 1.8
addons:
    apt:
        package:
            - docker-ce

# cache components
before_install:
    - docker pull airdb/alpine:latest
install:
      - if [ $TRAVIS_OS_NAME = linux ]; then echo linux; else echo xxx; fi
