notifications:
    email:
        - dean@airdb.com
dist: trusty
sudo: required
services:
      - docker
language: go
go:
    - 1.8
addons:
    apt:
        package:
            - docker-ce

# cache components
before_install:
    - docker pull airdb/alpine:latest
install:
      - if [ $TRAVIS_OS_NAME = linux ]; then echo linux; else echo xxx; fi
before_script:
    - docker run -it --rm airdb/alpine echo yes
script:
    #- docker build . -t airdb/vim -f image-based-alpine/vim.dockerfile
    - docker images | grep airdb/vim
after_success:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    #- curl -d "msg=Auto ci success.<br>cost: 60s.<br>https://travis-ci.org/airdb/sailor" http://airdb.com:9090/tarvis-ci/callback
after_failure:
    - echo
before_deploy:
    - echo
# deploy:
#     - curl airdb.com/deploy
after_deploy:
    - curl airdb.com/after_deploy
after_script:
    - echo
