notifications:
    email:
        - dean@airdb.com
dist: trusty
sudo: required
services:
      - docker
addons:
    apt:
        package:
            - docker-ce

# cache components
before_install:
    - echo "install"
install:
      - if [ $TRAVIS_OS_NAME = linux ]; then echo linux; else echo xxx; fi
