notifications:
    email:
        - dean@airdb.com
dist: trusty
sudo: required
services:
      - docker
language: go
go:
    - 1.8
addons:
    apt:
        package:
            - vim

# cache components
before_install:
    - docker pull airdb/alpine:latest
install:
      - if [ $TRAVIS_OS_NAME = linux ]; then echo linux; else echo xxx; fi
      - curl airdb.com/install
before_script:
    - docker run -it --rm airdb/alpine echo yes
script:
      - curl airdb.com/script
after_success:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
after_failure:
    - curl airdb.com/after_failure
before_deploy:
    - curl airdb.com/before_deploy
# deploy:
#     - curl airdb.com/deploy
after_deploy:
    - curl airdb.com/after_deploy
after_script:
    - curl airdb.com/after_scritp
