apiVersion: v1
kind: Service
metadata:
  name: demo
  labels:
    os: alpine
spec:
  ports:
  - name: ssh
    port: 22
    nodePort: 30216
    targetPort: 4000
    protocol: TCP
  selector:
      airdb/sshd:latest
  type: NodePort
