# -*- mode: ruby -*-
# vi: set ft=ruby :
# Copyright @ airdb.com

VAGRANTFILE_API_VERSION = "2"
NAME = "toolbox"
DOCKERFILE = "../base-image/alpine/lint.dockerfile"
IMAGE = "airdb/lint"
INIT_FILE = "../osinit/alpine_init.sh"

USER = ENV["USER"]
HOME = ENV["HOME"]
HOSTNAME = "#{NAME}.#{USER}.airdb.me"
RAW_PATH = "https://raw.githubusercontent.com/airdb/docker/master/vagrant"

File.exists?("#{HOME}/profile/.ssh/id_rsa") ? SSH_PRIVATE_KEY = "#{HOME}/profile/.ssh/id_rsa" : SSH_PRIVATE_KEY = "#{HOME}/.ssh/id_rsa"

ENV["LC_PORT"] = "8080"

Vagrant.configure("2") do |config|
  config.vm.define "#{NAME}" do | host |
    host.ssh.username = "root"
    host.ssh.shell = "/bin/sh"
    host.ssh.insert_key = true
    host.ssh.private_key_path = "#{SSH_PRIVATE_KEY}"

    host.vm.hostname = "#{HOSTNAME}"
    host.vm.provider "docker" do |d|
      if File.exists?("#{DOCKERFILE}")
        d.dockerfile = "#{DOCKERFILE}"
        d.build_dir = "./"
        d.build_args = ["--no-cache"]
        d.build_args = ["-t", "#{NAME}"]
      else
        d.image = "#{IMAGE}"
      end
      d.create_args = ["-e", "AAAA=11111"]
      d.name = "#{HOSTNAME}"
      d.privileged = true
      d.has_ssh = true
      d.cmd = ["/usr/sbin/sshd", "-D"]
      d.ports = ["4000:8080"]
      d.env = {
	    "SSH_PORT":"23"
      }
    end

    if File.exists?("#{INIT_FILE}")
      host.vm.provision "shell" do |s|
        s.path = "../osinit/alpine_init.sh"
        s.args = "base"
      end
    else
      host.vm.provision "shell", inline: "curl #{RAW_PATH}/#{INIT_FILE} | bash -s base"
    end
  end
end
